version: "3.7"
services:
    nodeserver:
        build:
            context: ./app
        volumes:
            - /usr/app/node_modules
        ports:
            - "5000:5000"
        stdin_open: true # docker run -i
        tty: true
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8010:8010"
    orthanc: 
        build:
            context: ./orthanc
        command: /run/secrets/  # Path to the configuration files (stored as secrets)
        ports:
            - 4242:4242
            - 8042:8042
        secrets:
          - orthanc.json
        environment:
          - ORTHANC_NAME=HelloWorld
secrets:
  orthanc.json:
    file: orthanc/orthanc.json